name: Run pytest

on:
  pull_request:
    types: [opened, reopened]
    branches: main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check for test skips
      - run: >
          skips="$(grep -r '@pytest.mark.skip' ./__tests__/)";
          if ["$skips" == ""];
          then echo "No pytest skips, happy days!";
          else echo "Skips were found in pytest, please remove them before merging to main" && exit 1;
          fi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipx
          pipx install poetry==2.0.1
          pipx ensurepath
          poetry install --with test
      - name: Run Linting
        run: poetry run mypy src/
      - name: Run tests
        run: poetry run pytest -v -s __tests__/
